services:
  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend
      - frontend
  backend:
    image: swunci/rss-feed-backend:latest
    expose:
      - 8081
    environment:
      - APP_ENV=production
    env_file:
      - ./.env.production
    volumes:
      - ./db-data:/app/data

  frontend:
    image: swunci/rss-feed-frontend:latest
    expose:
      - 8080
