services:
  server:
    build:
      context: .
      target: final
    environment:
      - APP_ENV=production
    env_file:
      - ./.env.production
    ports:
      - 8081:8081
    volumes:
      - db-data:/app/data
volumes:
  db-data:

