services:
  backend:
    image: swunci/rss-feed-backend:latest
    ports:
      - "38473:8081"
    environment:
      - APP_ENV=production
    env_file:
      - ./.env.production
    volumes:
      - ./db-data:/app/data

  frontend:
    image: swunci/rss-feed-frontend:latest
    ports:
      - "38472:80"
